version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    # Install dependencies and run tests
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - run:
          name: Fix apt lists directory permissions
          command: |
            sudo mkdir -p /var/lib/apt/lists/partial
            sudo chown -R _apt /var/lib/apt/lists
            sudo chmod 755 /var/lib/apt/lists
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update && apt-get install -y \
              libcairo2-dev \
              pkg-config \
              gstreamer1.0-tools \
              gir1.2-gstreamer-1.0 \
              gir1.2-gst-plugins-base-1.0 \
              gstreamer1.0-plugins-good \
              gstreamer1.0-plugins-ugly \
              gstreamer1.0-plugins-bad \
              gstreamer1.0-libav \
      - run:
          name: Install packages
          command: pip install pygobject PyObjC
      - run:
          name: Run tests
          command: python -m unittest discover tests/ '*_test.py' -v || ((($? == 5)) && echo 'Did not find any tests to run.')
  build-package:
    # build python package
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - python/dist
      - store_artifacts:
          path: dist
          destination: ~/artifacts
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  build-and-test:
    jobs:
      - test-python
      - build-package:
          requires:
            - test-python
    # - deploy:
    #     requires:
    #       - build-package
