version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    # Install dependencies and run tests
    docker:
      - image: cimg/python:3.8-node
    environment:
      GST_PLUGIN_SCANNER: "/usr/lib/x86_64-linux-gnu/gstreamer1.0/gst-plugin-scanner"
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
            gstreamer-1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            python3-gi \
            libgirepository1.0-dev \
            libcairo2-dev \
            alsa-utils \
            pulseaudio
      - run:
          name: Install Python dependencies
          command: |
            pip install pygobject
      - run:
          name: Setup virtual sound device
          command: |
            sudo modprobe snd-dummy
            cat /proc/asound/cards
            cat /proc/asound/modules
      - run:
          name: Run tests
          command: python -m unittest discover tests/ '*_test.py' -v || ((($? == 5)) && echo 'Did not find any tests to run.')
  build-package:
    # build python package
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - python/dist
      - store_artifacts:
          path: dist
          destination: ~/artifacts
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  build-and-test:
    jobs:
      - test-python
      - build-package:
          requires:
            - test-python
    # - deploy:
    #     requires:
    #       - build-package
